services:
  php:
    build: docker/php
    volumes:
      - .:/var/www/laravel:cached
    working_dir: /var/www/laravel
    environment:
# Laravelの.envはAPP_KEYのみにして、他はここで指定する
      - APP_NAME=prudential-to-moneyforward (local)
      - APP_ENV=local
      - APP_DEBUG=true
      - CACHE_DRIVER=file
      - SESSION_LIFETIME=1

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "15910:7900"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    shm_size: 2gb
